sudo: required
services:
  - docker

before_install:
  - docker build -t ilonao/react-test -f dockerfile .

script:
  - docker run -e CI=true ilonao/react-test npm test

deploy:
  on:
    branch: master
  # access_key_id: $AWS_ACCESS_KEY
  # secret_access_key:
  #   secure: "$AWS_SECRET_KEY"